#!/bin/sh
# vim: set ts=4:
set -eu

. "$(dirname "$0")"/common.sh


repos=''
for repo in main community testing; do
    repos="$repos $MIRROR_URI/$repo"
done

sudo sh -c "printf '%s\n' $repos > /etc/apk/repositories"
sudo apk update

title "Building all abuilds\n"
mkdir -p ~/buildlogs
buildrepo -ak -l ~/buildlogs "$CLONE_DIR" testing
